#!/bin/bash

BASE="/var/log/satellite"
LOG_PASS_STATUS="$BASE/monit_passenger.log"
LOG_PASS_MEMORY="$BASE/monit_passenger_memory.log"
LOG_PASS_REQS="$BASE/monit_passenger_requests.log"
LOG_WHOLE_PROCESS="$BASE/monit_whole_process.log"

mkdir -p $BASE
# Passenger status
cat <<ENDPASS >> $LOG_PASS_STATUS
$(date)
---B
$(passenger-status)
---E
ENDPASS

# Passenger memory status
cat <<ENDPASS >> $LOG_PASS_MEMORY
$(date)
---B
$(passenger-memory-stats)
---E
ENDPASS

# Passenger requests
cat <<ENDPASS >> $LOG_PASS_REQS
$(date)
---B
$(passenger-status --show=requests)
---E
ENDPASS

# Whole process
cat <<ENDPASS >> $LOG_WHOLE_PROCESS
$(date)
---B
$(ps -aux --sort -rss,pid)
---E
ENDPASS
